//! Centralised logging setup for memum-activity-bot.
//!
//! Initialises a three-layer `tracing-subscriber` stack:
//!
//!   * **Console layer** — coloured, human-readable output to stdout.
//!   * **File layer**    — plain-text, daily-rotating files written to `logs/`.
//!                         Files are named `YYYY-MM-DD.log` (UTC calendar day).
//!   * **Discord layer** — intercepts `error!` and `warn!` events and forwards
//!                         them to every guild that has a log channel configured.
//!
//! A custom panic hook converts panics into `error!` events so they flow
//! through all three layers automatically.
//!
//! # Call order in `main`
//!
//! ```rust,ignore
//! // 1. Init subscriber (before anything that might log)
//! let logging::LoggingSetup { discord_log_rx, _file_guard } = logging::init_logging();
//!
//! // 2. Install panic hook (must come after init_logging)
//! logging::install_panic_hook();
//!
//! // 3. After DB + Discord client are ready, spawn the Discord log worker
//! tokio::spawn(logging::discord_log_worker(discord_log_rx, db.clone(), client.http.clone()));
//!
//! // 4. Hold `_file_guard` alive until process exit — dropping it flushes and
//! //    stops the background file-writer thread.
//! ```

use std::fmt;
use std::sync::Arc;

use chrono::Utc;
use poise::serenity_prelude::{ChannelId, CreateEmbed, CreateMessage, Http};
use tokio::sync::mpsc;
use tracing::Level;
use tracing_subscriber::layer::SubscriberExt;
use tracing_subscriber::util::SubscriberInitExt;
use tracing_subscriber::{EnvFilter, Layer};

use crate::database::queries;

// ── Discord log entry ─────────────────────────────────────────────────────────

/// A single log event forwarded from the [`DiscordLayer`] to the async worker.
#[derive(Debug)]
pub struct DiscordLogEntry {
    /// Tracing level (`ERROR` or `WARN`).
    pub level: Level,
    /// Formatted log message (the `message` field of the tracing event).
    pub message: String,
    /// Module path of the originating code (e.g. `memum_activity_bot::sweeper`).
    pub target: String,
    /// Source file, if available (e.g. `src/sweeper/hypixel_sweeper.rs`).
    pub file: Option<&'static str>,
    /// Line number within that file, if available.
    pub line: Option<u32>,
    /// `true` when the event was generated by the panic hook.
    pub is_panic: bool,
}

// ── Field visitor ─────────────────────────────────────────────────────────────

/// Extracts the `message` and optional `panic` fields from a tracing event.
struct EventVisitor {
    message: String,
    is_panic: bool,
}

impl EventVisitor {
    fn new() -> Self {
        Self {
            message: String::new(),
            is_panic: false,
        }
    }
}

impl tracing::field::Visit for EventVisitor {
    /// Called for most fields, including the `message` field.
    ///
    /// The tracing `message` field is wrapped in a `field::DisplayValue`, whose
    /// `Debug` impl delegates to `Display` — so `format!("{value:?}")` yields
    /// the plain message string without surrounding quotes.
    fn record_debug(&mut self, field: &tracing::field::Field, value: &dyn fmt::Debug) {
        if field.name() == "message" {
            self.message = format!("{value:?}");
        }
    }

    /// Called when a field value is a plain `&str` (less common for `message`).
    fn record_str(&mut self, field: &tracing::field::Field, value: &str) {
        if field.name() == "message" {
            self.message = value.to_string();
        }
    }

    /// Detects the `panic = true` field written by [`install_panic_hook`].
    fn record_bool(&mut self, field: &tracing::field::Field, value: bool) {
        if field.name() == "panic" && value {
            self.is_panic = true;
        }
    }
}

// ── Discord tracing layer ─────────────────────────────────────────────────────

/// A [`tracing_subscriber::Layer`] that intercepts `ERROR` and `WARN` events
/// and enqueues them for the async Discord broadcast worker.
///
/// Events originating from this module are excluded to prevent feedback loops
/// (e.g. a DB failure inside the worker re-entering the channel indefinitely).
struct DiscordLayer {
    sender: mpsc::UnboundedSender<DiscordLogEntry>,
}

impl<S: tracing::Subscriber> Layer<S> for DiscordLayer {
    fn on_event(
        &self,
        event: &tracing::Event<'_>,
        _ctx: tracing_subscriber::layer::Context<'_, S>,
    ) {
        let meta = event.metadata();

        // Only forward ERROR and WARN — debug/info are too noisy for Discord.
        if *meta.level() > Level::WARN {
            return;
        }

        // Exclude events from this module to break potential feedback loops.
        if meta.target().starts_with("memum_activity_bot::logging") {
            return;
        }

        let mut visitor = EventVisitor::new();
        event.record(&mut visitor);

        let entry = DiscordLogEntry {
            level: *meta.level(),
            message: visitor.message,
            target: meta.target().to_string(),
            file: meta.file(),
            line: meta.line(),
            is_panic: visitor.is_panic,
        };

        // Unbounded send is sync and never blocks the caller.
        let _ = self.sender.send(entry);
    }
}

// ── Public types ──────────────────────────────────────────────────────────────

/// Receiving end of the Discord log channel. Pass to [`discord_log_worker`].
pub type DiscordLogReceiver = mpsc::UnboundedReceiver<DiscordLogEntry>;

/// Returned by [`init_logging`]. The caller **must** hold this value for the
/// entire lifetime of the process.
///
/// Dropping `_file_guard` causes the background file-writing thread to flush
/// and stop, which can truncate the last batch of log lines.
pub struct LoggingSetup {
    /// Receive end — hand this to [`discord_log_worker`] after the DB and HTTP
    /// client are available.
    pub discord_log_rx: DiscordLogReceiver,
    /// File appender thread guard. Must stay alive for file writes to continue.
    pub _file_guard: tracing_appender::non_blocking::WorkerGuard,
}

// ── init_logging ──────────────────────────────────────────────────────────────

/// Initialise the global tracing subscriber with three layers:
///
/// | Layer   | Output              | Format            | Filter           |
/// |---------|---------------------|-------------------|------------------|
/// | Console | stdout              | coloured + target | `RUST_LOG` / default |
/// | File    | `logs/YYYY-MM-DD.log` | plain text      | same             |
/// | Discord | async channel       | embed             | ERROR + WARN     |
///
/// Must be called **once**, before any `tracing` macros are used.
/// Returns a [`LoggingSetup`] that must be kept alive.
pub fn init_logging() -> LoggingSetup {
    // ── Daily-rotating file appender ─────────────────────────────────────────
    // Files are named logs/YYYY-MM-DD.log.
    // tracing-appender creates the `logs/` directory automatically.
    let file_appender = tracing_appender::rolling::RollingFileAppender::builder()
        .rotation(tracing_appender::rolling::Rotation::DAILY)
        .filename_suffix("log")
        .build("logs")
        .expect("failed to initialise log file appender");

    let (non_blocking_file, file_guard) = tracing_appender::non_blocking(file_appender);

    // ── Discord broadcast channel ─────────────────────────────────────────────
    let (discord_tx, discord_rx) = mpsc::unbounded_channel::<DiscordLogEntry>();

    // ── EnvFilter ─────────────────────────────────────────────────────────────
    // Reads the RUST_LOG environment variable; falls back to INFO for this
    // crate and WARN for all transitive dependencies.
    let env_filter = EnvFilter::try_from_default_env()
        .unwrap_or_else(|_| EnvFilter::new("memum_activity_bot=info,warn"));

    // ── Console layer ─────────────────────────────────────────────────────────
    // Coloured output with file + line information for easy triage.
    let console_layer = tracing_subscriber::fmt::layer()
        .with_target(true)
        .with_file(true)
        .with_line_number(true);

    // ── File layer ────────────────────────────────────────────────────────────
    // Identical fields but ANSI escape codes stripped (plain text on disk).
    let file_layer = tracing_subscriber::fmt::layer()
        .with_writer(non_blocking_file)
        .with_ansi(false)
        .with_target(true)
        .with_file(true)
        .with_line_number(true);

    // ── Discord layer ─────────────────────────────────────────────────────────
    let discord_layer = DiscordLayer { sender: discord_tx };

    // ── Assemble ──────────────────────────────────────────────────────────────
    tracing_subscriber::registry()
        .with(env_filter)
        .with(console_layer)
        .with(file_layer)
        .with(discord_layer)
        .init();

    LoggingSetup {
        discord_log_rx: discord_rx,
        _file_guard: file_guard,
    }
}

// ── Panic hook ────────────────────────────────────────────────────────────────

/// Install a panic hook that converts panics into `error!` events.
///
/// This ensures every panic is captured by all three logging layers:
/// console, file, and Discord. Must be called **after** [`init_logging`].
pub fn install_panic_hook() {
    std::panic::set_hook(Box::new(|info| {
        let location = info
            .location()
            .map(|l| format!("{}:{}:{}", l.file(), l.line(), l.column()))
            .unwrap_or_else(|| "unknown location".to_string());

        let message = if let Some(s) = info.payload().downcast_ref::<&str>() {
            s.to_string()
        } else if let Some(s) = info.payload().downcast_ref::<String>() {
            s.clone()
        } else {
            "(panic with non-string payload)".to_string()
        };

        // The `panic = true` field is detected by EventVisitor in DiscordLayer,
        // which causes the Discord embed to show a 💥 Panic title instead of ❌ Error.
        tracing::error!(
            panic = true,
            location = %location,
            "PANIC: {message}",
        );
    }));
}

// ── Discord log worker ────────────────────────────────────────────────────────

/// Async worker that drains [`DiscordLogEntry`] values from the channel and
/// broadcasts each one to every guild that has a log channel configured.
///
/// Spawn this task **after** the Serenity HTTP client and database pool are
/// ready. It runs for the lifetime of the process.
///
/// Errors that occur inside this worker are sent to console + file via
/// `tracing::error!`. Because [`DiscordLayer`] filters out events from
/// `memum_activity_bot::logging`, these errors will not re-enter the channel.
pub async fn discord_log_worker(mut rx: DiscordLogReceiver, pool: sqlx::PgPool, http: Arc<Http>) {
    tracing::info!("Discord log worker started.");

    while let Some(entry) = rx.recv().await {
        let guilds = match queries::get_all_guild_log_channels(&pool).await {
            Ok(g) => g,
            Err(e) => {
                // Intentionally use tracing::error! here — the DiscordLayer
                // filters this module's target, so it won't loop back.
                tracing::error!(
                    error = %e,
                    "Discord log worker: failed to fetch guild log channels."
                );
                continue;
            }
        };

        for (_guild_id, channel_id) in guilds {
            let embed = build_discord_embed(&entry);
            let channel = ChannelId::new(channel_id as u64);
            let _ = channel
                .send_message(&http, CreateMessage::new().embed(embed))
                .await;
        }
    }

    tracing::warn!("Discord log worker channel closed — worker exiting.");
}

// ── Embed builder ─────────────────────────────────────────────────────────────

/// Build a richly formatted Discord embed for an automatic log entry.
///
/// | Level   | Title     | Colour  |
/// |---------|-----------|---------|
/// | Panic   | 💥 Panic  | Red     |
/// | ERROR   | ❌ Error  | Red-ish |
/// | WARN    | ⚠️ Warning | Yellow  |
fn build_discord_embed(entry: &DiscordLogEntry) -> CreateEmbed {
    let (title, color): (&str, u32) = if entry.is_panic {
        ("💥 Panic", 0xFF0000)
    } else if entry.level == Level::ERROR {
        ("❌ Error", 0xe74c3c)
    } else {
        ("⚠️ Warning", 0xf1c40f)
    };

    let timestamp = Utc::now().format("%Y-%m-%d %H:%M:%S UTC").to_string();

    let location = match (entry.file, entry.line) {
        (Some(file), Some(line)) => format!("`{file}:{line}`"),
        (Some(file), None) => format!("`{file}`"),
        _ => "unknown".to_string(),
    };

    CreateEmbed::new()
        .title(title)
        .description(&entry.message)
        .color(color)
        .field("Module", &entry.target, true)
        .field("Location", location, true)
        .field("Time", timestamp, false)
}
